### ISSUE TITLE
Issue listening for playBytes topic

### ISSUE THREAD

**Issue by bastiaanterhorst** [rhasspy/rhasspy-hermes-app#114]
I am trying to move audio playing from Rhasspy to my own intent handling app built using rhasspy-hermes-app. I figured the [example here](https://github.com/rhasspy/rhasspy-hermes-app/blob/master/examples/raw_topic_list_app.py) would be a great place to start.

Unfortunately, I can't even get that example app to function properly. When I run it and speak the wake word, I get the following output:

```
/home/pi/.local/lib/python3.7/site-packages/rhasspyhermes_app/__init__.py:259: RuntimeWarning: coroutine 'HermesApp.on_topic.<locals>.wrapper.<locals>.wrapped' was never awaited
  function_2(data, payload)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

I'm pretty new to Python so this is a bit challenging for me to debug. If someone could point me in the right direction that would be highly appreciated.

**Comment by koenvervloesem** [comment]
It seems you have hit this bug:

https://github.com/rhasspy/rhasspy-hermes-app/pull/89/files

It's already fixed by the above PR, but not yet released. For now you could do the one-line fix in your local copy of rhasspy-hermes-app by editing `/home/pi/.local/lib/python3.7/site-packages/rhasspyhermes_app/__init__.py`.

**Comment by bastiaanterhorst** [comment]
Actually I think I might have found a bug?

When I dive into HermesApp::on_raw_message (line 259) and add an `await` statement before the function call, the error goes away and the example works again.

**Comment by bastiaanterhorst** [comment]
Gotcha, I found the same you mentioned I think. Thanks for the info!

**Comment by koenvervloesem** [comment]
Release 1.1.2 with the fix has been published now: https://github.com/rhasspy/rhasspy-hermes-app/releases/tag/v1.1.2
