### ISSUE TITLE
Change Standard Port to 12183 - Discussion

### ISSUE THREAD

**Issue by JonahKr** [rhasspy/rhasspy-hermes-app#14]
Since this App is rhasspy specific, it maybe would make sense to change the port from 1883 to 12183 which is the standard port rhasspy hosts its mqtt server on.

Altough it would make sense to keep it at 1883 if the user where to use a external mqtt broker.

Comment what you think about this.

**Comment by koenvervloesem** [comment]
It all depends on what you consider the default situation. For me that's a central MQTT server, but I understand that someone who doesn't use MQTT outside Rhasspy doesn't think the same way.

I'll think about this.

**Comment by maxbachmann** [comment]
by the way why do we even use 12183 as the port for rhasspy :sweat_smile: 
I personally always map this port to 1883, since I keep forgetting the port number.

**Comment by JonahKr** [comment]
i think its because for setups with satelites it was normal to use a external mqtt broker? however i don't see any problem of using the internal one on the master node tbh...

**Comment by koenvervloesem** [comment]
I will keep 1883 as the default port. It's also like this [in rhasspy-hermes](https://github.com/rhasspy/rhasspy-hermes/blob/master/rhasspyhermes/cli.py) and it's generally known as the default port for MQTT. So using 12183 as the default one would be confusing.
