### ISSUE TITLE
Raspberry PI OS Bullseye Python 3.9.2 Supported?

### ISSUE THREAD

**Issue by SteveShantz** [rhasspy/rhasspy-hermes-app#161]
On a Raspberry Pi 4, I'm using Rhasspy 2.5.11 and processing the intents in my Python program using rhasspy-hermes-app. This was working fine when I was running the Buster version of the Raspberry Pi OS. I just upgraded to the recent Raspberry Pi OS that is using Bullseye. Now it has stopped working. When I give a voice command I get the following error:

`ERROR:HermesApp:on_raw_message
Traceback (most recent call last):
  File "/home/norwolf/.local/lib/python3.9/site-packages/rhasspyhermes_app/__init__.py", line 208, in on_raw_message
    nlu_intent = NluIntent.from_json(payload)
  File "/home/norwolf/.local/lib/python3.9/site-packages/dataclasses_json/api.py", line 72, in from_json
    kvs = json.loads(s,
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'`

Upgrading the Raspberry PI OS also changed the Python version from 3.7.3 to 3.9.2.

Is rhasspy-hermes-app supported on Bullseye and Python 3.9.2? Or am I experiencing a different problem?

Thanks

**Comment by SteveShantz** [comment]
Looks like there were problems with the initial Raspberry Pi OS release using Bullseye.

https://www.tomshardware.com/news/raspberry-pi-releases-legacy-os

Maybe this is the reason for the issues I was seeing.

**Comment by koenvervloesem** [comment]
'was' as in you don't see this error anymore? I haven't tried rhasspy-hermes-app yet on Bullseye, I should be able to set up a brand new Raspberry Pi OS system soon.

**Comment by SteveShantz** [comment]
> 'was' as in you don't see this error anymore? I haven't tried rhasspy-hermes-app yet on Bullseye, I should be able to set up a brand new Raspberry Pi OS system soon.

The error is still being seen, but I've also not done anything to try and resolve it. I was just wondering, based upon the tomshardware article, if the issue was due to OS problems as opposed to rhasspy-hermes-app problems.

**Comment by ep1cman** [comment]
I get the same issue running on my mac with python >= 3.9, the encoding parameter has been removed from the json decoder: https://docs.python.org/3/library/json.html#json.loads

The problem actually lies in `rhasspy-hermes`, it needs to bump to a newer version of `dataclasses_json` which resolves this issue

**Comment by koenvervloesem** [comment]
@ep1cman Thanks for figuring this out! I've fixed Python 3.9 support in rhasspy-hermes now, there were some other issues as well. I'll publish a new release soon.

**Comment by koenvervloesem** [comment]
@SteveShantz Can you upgrade rhasspy-hermes to version 0.6.2 and try again whether your Python program works now on Bullseye?

**Comment by SteveShantz** [comment]
@koenvervloesem I've just upgraded rhasspy-hermes to 0.6.2 and it now works on Bullseye. I then changed back 0.6.1 and the error happens. 

So 0.6.2 solves the problem. Sorry for the delay in testing this.

**Comment by koenvervloesem** [comment]
Thanks for testing!
