### ISSUE TITLE
ERROR: Could not install packages due to an EnvironmentError

### ISSUE THREAD

**Issue by achintyaakumar** [rhasspy/rhasspy-hermes-app#42]
I run the `pip3 install rhasspy-hermes-app` command on my Ubuntu 20.04 virtualbox running on a windows 10 PC and get the following error message. 

`Defaulting to user installation because normal site-packages is not writeable
Collecting rhasspy-hermes-app
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)'))': /packages/25/40/078fe07023a34b77321915b0313e9d41d1e024e79c5b23287bd7d19c8e6e/rhasspy-hermes-app-1.0.0.tar.gz
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)'))': /packages/25/40/078fe07023a34b77321915b0313e9d41d1e024e79c5b23287bd7d19c8e6e/rhasspy-hermes-app-1.0.0.tar.gz
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)'))': /packages/25/40/078fe07023a34b77321915b0313e9d41d1e024e79c5b23287bd7d19c8e6e/rhasspy-hermes-app-1.0.0.tar.gz
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)'))': /packages/25/40/078fe07023a34b77321915b0313e9d41d1e024e79c5b23287bd7d19c8e6e/rhasspy-hermes-app-1.0.0.tar.gz
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)'))': /packages/25/40/078fe07023a34b77321915b0313e9d41d1e024e79c5b23287bd7d19c8e6e/rhasspy-hermes-app-1.0.0.tar.gz
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/25/40/078fe07023a34b77321915b0313e9d41d1e024e79c5b23287bd7d19c8e6e/rhasspy-hermes-app-1.0.0.tar.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))`

Any ideas as to why this might be happening?

**Comment by koenvervloesem** [comment]
That's weird, a certificate error with files.pythonhosted.org? This seems to be [a network issue](https://github.com/pypa/pip/issues/7663). Is there anything special about your network that changes TLS certificates or DNS resolving?

**Comment by achintyaakumar** [comment]
@koenvervloesem not that I'm aware of. I am using a work laptop tho so I wonder if this is a firewall issue? Is there any other way I could install the app without using pip?

**Comment by koenvervloesem** [comment]
It could be a firewall issue. Have you taken a look at the suggestions in the link above?

Or maybe it has something to do with the VirtualBox network?

You can always do an install from the source: git pull the repo and then pip3 install -e.

**Comment by achintyaakumar** [comment]
It's not Virtualbox, I'm getting the same error on Windows. My best guess is it's either a firewall or some restrictions put in place by the corporate IT. I will contact them and post here if I find a solution. 
I'm trying the other way by cloning the repo, what command should I run to install it? Thanks for your help! @koenvervloesem

**Comment by achintyaakumar** [comment]
Got it! Running `pip3 install --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org rhasspy-hermes-app` worked!
