### ISSUE TITLE
KeyError: 'entity' on intent recognition

### ISSUE THREAD

**Issue by EinfachArne** [rhasspy/rhasspy-hermes-app#7]
Hi,

thank you a lot for this great library. I tried to develop my own app using your work but unfortunately I get an error as soon as my intent is recognised:

    [DEBUG:2020-06-06 15:39:35,283] asyncio: Using proactor: IocpProactor
    [DEBUG:2020-06-06 15:39:35,284] OpenHABSwitchOnApp: Connected to MQTT broker
    [DEBUG:2020-06-06 15:39:35,285] OpenHABSwitchOnApp: Subscribed to hermes/intent/SwitchOn
    [ERROR:2020-06-06 15:39:39,386] HermesApp: on_raw_message
    Traceback (most recent call last):
    File "C:\Users\Arne\AppData\Roaming\Python\Python38\site-packages\rhasspyhermes_app\__init__.py", line 62, in on_raw_message
        nlu_intent = NluIntent.from_json(payload)
    File "C:\Users\Arne\AppData\Roaming\Python\Python38\site-packages\dataclasses_json\api.py", line 78, in from_json
        return cls.from_dict(kvs, infer_missing=infer_missing)
    File "C:\Users\Arne\AppData\Roaming\Python\Python38\site-packages\dataclasses_json\api.py", line 85, in from_dict
        return _decode_dataclass(cls, kvs, infer_missing)
    File "C:\Users\Arne\AppData\Roaming\Python\Python38\site-packages\dataclasses_json\core.py", line 192, in _decode_dataclass
        init_kwargs[field.name] = _decode_generic(field_type,
    File "C:\Users\Arne\AppData\Roaming\Python\Python38\site-packages\dataclasses_json\core.py", line 266, in _decode_generic
        res = _decode_generic(type_arg, value, infer_missing)
    File "C:\Users\Arne\AppData\Roaming\Python\Python38\site-packages\dataclasses_json\core.py", line 254, in _decode_generic
        res = _get_type_cons(type_)(xs)
    File "C:\Users\Arne\AppData\Roaming\Python\Python38\site-packages\dataclasses_json\core.py", line 297, in <genexpr>
        items = (_decode_dataclass(type_arg, x, infer_missing)
    File "C:\Users\Arne\AppData\Roaming\Python\Python38\site-packages\dataclasses_json\core.py", line 150, in _decode_dataclass
        field_value = kvs[field.name]
    KeyError: 'entity'

This is the corresponding intent:
`[SwitchOn]
schalte (das | den | die) $item{item} an`

And this is my code:

    import logging

    from rhasspyhermes_app import HermesApp

    _LOGGER = logging.getLogger("OpenHABSwitchOnApp")

    app = HermesApp("OpenHABSwitchOnApp")

    @app.on_intent("SwitchOn")
    def switch_on(intent):

        return app.EndSession("test")

    app.run()

Did I make any mistake in my app or is this a bug in the library?

**Comment by koenvervloesem** [comment]
Can you show the output of the following command while the intent is activated?

```shell
mosquitto_sub -t 'hermes/#' -T 'hermes/audioServer/+/playBytes/+' -T 'hermes/audioServer/+/audioFrame' -v
```

**Comment by EinfachArne** [comment]
This is the output:

	hermes/intent/SwitchOn {"sessionId": "", "siteId": "default", "input": "schalte den fernseher an", 
	"intent": {"intentName": "SwitchOn", "confidenceScore": 1.0}, "slots": [{"slotName": "item", 
	"confidence": 1, "value": {"kind": "item", "value": "fernseher"}, "rawValue": "fernseher"}], 
	"asrTokens": [], "asrConfidence": 1}

**Comment by koenvervloesem** [comment]
It seems your slot doesn't have an entity. What is your setup exactly? Which intent recognition engine are you using?

**Comment by EinfachArne** [comment]
This is the setup I use:

![setup_rhasspy](https://user-images.githubusercontent.com/42092210/83953867-642af200-a844-11ea-8f08-59f1decd24bd.JPG)

Do you need to know more about my setup?

**Comment by koenvervloesem** [comment]
Thanks. This looks like a bug in [Rhasspy Hermes](https://github.com/rhasspy/rhasspy-hermes). I'll take a closer look later.

**Comment by koenvervloesem** [comment]
I think I'm beginning to understand the problem. Are you using Rhasspy 2.4?

**Comment by EinfachArne** [comment]
Yes, I do. 2.4.20 to be exact. Should I upgrade to 2.5 now that it is released?

**Comment by koenvervloesem** [comment]
Well, this library is not tested with Rhasspy 2.4. Upgrading is recommended.

That should solve your problem, but you have uncovered a bug with the way rhasspy-hermes-app handles unexpected payloads, it should be more resilient. Thanks for submitting your bug report, I will fix this later.

**Comment by EinfachArne** [comment]
Thank you. I upgraded to 2.5 and it seems to work now. And sorry for not noticing that this project is based on Rhasspy 2.5 but I see that you already added a note to the readme.

**Comment by koenvervloesem** [comment]
No problem! I haven't been using the 2.4 branch myself anymore for a long time, so it's good that this bug report made me aware of the incompatibility so I could make this explicit in the documentation.

In the mean time I have fixed the code so it doesn't stop when receiving an unexpected payload but logs an error message with all the details: https://github.com/rhasspy/rhasspy-hermes-app/commit/5bce30ca728429292747bd3e8c96bec8505a906b.
